openapi: 3.0.0
info:
  version: 0.0.4
  title: Events Collector API
  description: >-
    Beckn network components can use this API to remmit events to track the
    Transaction history.
paths:
  /event:
    post:
      tags:
        - CreateEvent
      summary: Create an event
      requestBody:
        description: Event object for the application to log events
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event could not be created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Event:
      description: Object to create a new event
      type: object
      required:
        - experienceId
        - eventCode
        - eventTitle
        - eventMessage
        - eventSource
        - eventDestination
        - eventSourceId
        - eventStart_ts
        - created_ts
      properties:
        experienceId:
          type: string
          description: Session id (unique id based on domain and app details)
        eventId:
          type: string
          description: Event id (unique id that was created as a result of new event)
        eventCode:
          type: string
          description: Event code 
        eventTitle:
          type: string
          description: Event title
        eventMessage:
          type: string
          description: Event message to be displayed
        eventSource:
          $ref: '#/components/schemas/EventSource'
        eventDestination:
          $ref: '#/components/schemas/EventDestination'
        context:
          $ref: '#/components/schemas/Context'
        payload:
          type: string
        eventStart_ts:
          type: string
          description: Time when the event is started
        eventEnd_ts:
          type: string
          description: Time when the event was completed
        created_ts:
          type: string
          description: Time when the event is created
        lastModified_ts:
          type: string
          description: Time when the event was last modified
    EventSource:
      description: Event source details
      type: object
      required:
        - eventSourceType
      properties:
        eventSourceId:
          type: string
          description: Application id for source
        eventSourceType:
          type: string
          description: Source of event (BAP, BPP, GW etc)
          enum:
            - bap
            - bpp
            - gateway
    EventDestination:
      description: Event destination details
      type: object
      required:
        - eventDestinationType
      properties:
        eventDestinationId:
          type: string
          description: Application id for target
        eventDestinationType:
          type: string
          description: Destination for event (BAP, BPP, GW etc)
          enum:
            - bap
            - bpp
            - gateway
    Context:
      description: Protocol context 
      type: object
      required:
        - transactionId
        - messageId
      properties:
        transactionId:
          type: string
          description: Protocol transaction id from context
        messageId:
          type: string
          description: Protocol message id from context
    Error:
      type: object
      required:
        - message
      properties:
        type:
          description: Type of error
          type: string
        code:
          description: Event specific error code
          type: string
        path:
          description: Path to json schema generating the error. Used only during json schema validation errors
          type: string
        message:
          description: Human readable error message from event collector API
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
servers:
  - url: https://api.eventcollector.becknprotocol.io
    variables: {}
